### ISSUE TITLE
Questionable behaviour due to chosing icon themes lacking icons expected by LXQt ConnMan Applet

### ISSUE THREAD

**Issue by pmattern** [lxqt/lxqt-connman-applet#12]
When icon themes are chosen which don't cover all icon names LXQt ConnMan Applet is normally considering the display of icons gets faulty.

E. g. icon theme breeze is providing an icon `network-wired` but neither `network-offline` nor `network-wireless-signal-*-symbolic`. If it's chosen on a system with Ethernet connections only there's icon `network-wired`
![lxqt-connman-applet_incomplete-icon-themes_breeze-network-wired](https://cloud.githubusercontent.com/assets/9860801/19359940/9ff7e654-917c-11e6-9d97-85edcbba4f5e.png)
in the panel, on systems with WLAN connections only it's `gtk-execute`
![lxqt-connman-applet_incomplete-icon-themes_breeze-gtk-execute](https://cloud.githubusercontent.com/assets/9860801/19359967/bf1dc08a-917c-11e6-91c5-e63b3fcd7554.png)
or `dialogue-information`.
All these icons are displayed all the time, no matter whether or not a connection is established.

Not sure what's best to do here, e. g. if LXQt ConnMan Applet should replace icons missing in a particular icon theme with its own SVG icons or e. g. refuse to use the icon theme and throw a warning. But the current behaviour is rather confusing.

Seen running 41126c9 with recent LXQt on Arch Linux.

**Comment by surlykke** [comment]
Thanks for the bug-report. I'm looking into it.

**Comment by surlykke** [comment]
Does 7cac47293150f29355c799efe63f2aad57884853 + f0c9425c5e4807b6a171a7752872e50b374e64e9 help?

What the code tries to do is: Look for sets of icon-names. There is a set you'd expect to see when theme is oxygen or breeze, another set when theme is gnome, adwaita, awoken and probably others. If non of these sets are found we fall (fully) back to built in icons. (See IconProducer::onIconThemeChanged()).

**Comment by pmattern** [comment]
Problem can be considered as fixed in f0c9425.

When an icon theme is chosen that's featuring all icons which are defined in those `if()` stanzas like [this one](https://github.com/surlykke/lxqt-connman-applet/blob/f0c9425c5e4807b6a171a7752872e50b374e64e9/iconproducer.cpp#L58-L64) the corresponding icons are used. When an icon theme is chosen that does not provide the full set of icons as defined in those stanzas LXQt ConnMan Applet is falling back to its genuine SVG icons.

The UX still isn't really good, IMO, which is more due to the not exactly consistent way icon names are dealt with.
E. g. `network-wired` is depicting a wired connection without making a statement about the connection status in Breeze, in Adwaita it's a plugged cable, in Faenza, Faience and Numix it's an empty jack and in Oxygen an unplugged cable next to an empty jack.
So I think this problem can pretty obviously not be solved with reasonable effort at the level of tools like LXQt ConnMan Applet but only by a more consistent handling of icon names by the upstream theme maintainers.

Similarly, it may make sense to add additional `if()` stanzas one day. But that's not really related to this issue any longer and certainly not on the agenda right now.
