### ISSUE TITLE
CMake error while building from source.

### ISSUE THREAD

**Issue by dariusity** [lxqt/lxqt-connman-applet#25]
When I was trying to build this source, I encountered the following error;

       CMake Error at iconviewer/CMakeLists.txt:6 (qt5_add_resources):
       Unknown CMake command "qt5_add_resources".

Please let me know how can I solve this issue.
I am on Manjaro Community Edition of LXQt 0.14.1;
Machine spec Compaq Presario CQ40-141TU;
Intel P7350 Core2 Duo Processor with Compal 3670 Mobo;
Running on 3 GB RAM, sole OS in the 500GB Toshiba MQ01ABF050;
Kernel 4.19.30-1-MANJARO x86_64.

Thanks.

**Comment by tsujan** [comment]
Confirmed.

It seems that this program hasn't been actively developed. I use and highly recommend [CMST](https://github.com/andrew-bibb/cmst).

**Comment by agaida** [comment]
connman-applet can be a wonderful companion for cmst. But it need a bit love. Will fix the cmake things later, it's just about the order in CMakeLists.txt

**Comment by dariusity** [comment]
Thanks for the prompt reply guys, can I ask off topic questions? There are 2 things regarding lxqt-panel I'd like to address;

1) the panel theme, Frost was dark in color before the 0.14.1 update & now it has turned into light color. I am using the Dark theme now & the menu opacity is so much hassle to config & barely can see the font. I tried to edit options like menu opacity=1 in both the compton.conf and the Windows Effects GUI but no changes can be seen. I also have tried the other way around to menu opacity=0 at both the mentioned options earlier and still don't see any movements at all. My questions would be;

1) can the menu opacity of Dark theme be changed to solid black? 
2) is the Frost theme going to be permanently light or there is a way to edit the source?

3) what are the latest environment setup to be used? I have only 'QT_QPA-PLATFORMTHEME=qt5ct' which I added myself.

**Comment by tsujan** [comment]
Off-topic answers:

  1. Frost hasn't changed and wasn't dark: it reverses colors, which means that if you have a light widget style it'll be dark and if you have a dark widget style it'll be light.

  2. You could copy any theme folder from `/usr/share/lxqt/themes`, paste it into `~/.local/share/lxqt/themes` and edit it as you like.

  3. Read 1.

  4. Under LXQt, set `QT_QPA_PLATFORMTHEME` to `lxqt`. Not only you don't need `qt5ct` under LXQt but also it can meddle with styles. Actually, you could do the same outside LXQt too (but not under KDE).

Please ask such questions on the forum!

**Comment by tsujan** [comment]
> connman-applet can be a wonderful companion for cmst.

I've never needed it but if it's good, it needs more attention, as you said.

**Comment by dariusity** [comment]
Cheers guys thanks for taking your time to clarify my questions. I'll die a happy man, take care.
