### ISSUE TITLE
problems with IEEE8021x wifi networks

### ISSUE THREAD

**Issue by excalibur1234** [lxqt/lxqt-connman-applet#3]
i can connect to ethernet and almost all wifi networks in my surrounding without problems.

it is easy to connect to open wifi networks.
it is easy to connect to wps and/or psk protected wifi networks: i just have to enter the right password.
it is impossible to connect to a IEEE8021x protected wifi network, because i never see a window in which i can enter my username and password.

i have observed the same behavior with https://github.com/andrew-bibb/cmst. therefore, i think it might be a problem of connman.
so, is it a problem of lxqt-connman-applet or connman?
do you know more about it?

**Comment by surlykke** [comment]
2015-04-10 19:01 GMT+02:00 excalibur1234 notifications@github.com:

> i can connect to ethernet and almost all wifi networks in my surrounding
> without problems.
> 
> it is easy to connect to open wifi networks.
> it is easy to connect to wps and/or psk protected wifi networks: i just
> have to enter the right password.
> it is impossible to connect to a IEEE8021x protected wifi network, because
> i never see a window in which i can enter my username and password.
> 
> i have observed the same behavior with https://github.com/andrew-bibb/cmst.
> therefore, i think it might be a problem of connman.
> so, is it a problem of lxqt-connman-applet or connman?
> do you know more about it?
> 
> Sorry - no. Haven't tried it. Maybe you could try with connmanctl ?

br. Chr.

**Comment by excalibur1234** [comment]
thanks for your reply. i did some tests with connmanctl. it looks like it really is a bug in connman.

i did the following:

```
$ connmanctl
connmanctl> scan wifi
connmanctl> services
connmanctl> agent on
```

next, when i connect to a psk managed wifi

```
connmanctl> connect wifi_001e899ae682_55736311_managed_psk
```

i get: 

```
Agent RequestInput wifi_001e899ae682_55736311_managed_psk
  Passphrase = [ Type=psk, Requirement=mandatory, Alternates=[ WPS ] ]
  WPS = [ Type=wpspin, Requirement=alternate ]
Passphrase? 
```

but when i connect to a ieee8021x managed wifi

```
connmanctl> connect wifi_001e899ae682_4861446946756d4d_managed_ieee8021x
```

i get:

```
Error /net/connman/service/wifi_001e899ae682_486144694675d4d_managed_ieee8021x: Invalid arguments
```

**Comment by surlykke** [comment]
2015-04-10 22:34 GMT+02:00 excalibur1234 notifications@github.com:

> thanks for your reply. i did some tests with connmanctl.
> 
> i did the following:
> $ connmanctl
> connmanctl> scan wifi
> connmanctl> services
> connmanctl> agent on
> 
> next, when i connect to a
> connmanctl> connect wifi_001e899ae682_55736311_managed_psk
> i get:
> Agent RequestInput wifi_001e899ae682_55736311_managed_psk
> Passphrase = [ Type=psk, Requirement=mandatory, Alternates=[ WPS ] ]
> WPS = [ Type=wpspin, Requirement=alternate ]
> Passphrase?
> 
> when i do a
> connmanctl> connect wifi_001e899ae682_4861446946756d4d_managed_ieee8021x
> i get:
> Error
> /net/connman/service/wifi_001e899ae682_486144694675d4d_managed_ieee8021x:
> Invalid arguments
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/surlykke/lxqt-connman-applet/issues/3#issuecomment-91679062
> .
> 
> Ok - seems to be a connman problem then. You're probably better of trying
> to raise the issue there.

br. Chr.

**Comment by excalibur1234** [comment]
i somehow cannot create an account on their bugtracker: https://01.org/jira/browse/CM
i am also trying their IRC, but despite 50 people being only, nobody answers.

i will keep trying. thanks for your help.

**Comment by excalibur1234** [comment]
for all future readers: you need to manually create a provisioning file before you can connect to an IEEExxx network. look here for a very short description: 
https://github.com/andrew-bibb/cmst/wiki/Eduroam-and-IEEE802x
