### ISSUE TITLE
FTBFS on recent VCS checkout of LXQt

### ISSUE THREAD

**Issue by pmattern** [lxqt/lxqt-connman-applet#5]
Apparently lxqt-connman-applet doesn't built on LXQt from latest VCS checkout any longer, maybe due to the lots of changes that took place under the hood recently:

```
$ cmake . 
[...]
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:14 (include):
  include called with wrong number of arguments.  include() only takes one
  file.

CMake Error at CMakeLists.txt:15 (include):
  include called with wrong number of arguments.  include() only takes one
  file.
```

The very same command as well as `make` thereafter run flawlessly on a system using an LXQt Git checkout from 2015-06-30.

Arch Linux i686 or x86_64 (same findings).

**Comment by surlykke** [comment]
I'm just between laptops - hopefully I'll be able to look at it in the
weekend.

Br. Chr.
Den 07/07/2015 20.09 skrev "Peter Mattern" notifications@github.com:

**Comment by surlykke** [comment]
Can you check if 98827f9 helps?
- Chr.

**Comment by pmattern** [comment]
98827f9 compiles and works flawlessly on up-to-date Arch Linux running all LXQt components from latest Git checkout, both i686  and x86_64.

Issue can be closed, IMO.

**Comment by surlykke** [comment]
Thanks for reporting and testing !
