### ISSUE TITLE
CMake Error at CMakeLists.txt:89 (lxqt_translate_desktop): Unknown CMake command "lxqt_translate_desktop".

### ISSUE THREAD

**Issue by benkohler** [lxqt/lxqt-connman-applet#7]
Hello,

Since the cmake changes in commit 98827f9cd4b8c8de1111c843932cf05864312f79, I can't build lxqt-connman-applet anymore.  I hope this isn't my local issue but I don't think it is.  I don't know cmake at all but it would appear that dropping "include(${LXQT_USE_FILE})" makes it unable to find lxqt_translate_desktop.  

If I keep all changes from this commit but stick that one include line back in, all is well.  Not sure what the actual proper fix is, though.  Let me know if you need any more info from me.

Thanks!

**Comment by benkohler** [comment]
cmake --no-warn-unused-cli -C /var/tmp/portage/net-misc/lxqt-connman-applet-0_p20150712/work/lxqt-connman-applet-0_p20150712_build/gentoo_common_config.cmake -G Unix Makefiles -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_INSTALL_DO_STRIP=OFF -DCMAKE_USER_MAKE_RULES_OVERRIDE=/var/tmp/portage/net-misc/lxqt-connman-applet-0_p20150712/work/lxqt-connman-applet-0_p20150712_build/gentoo_rules.cmake -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/net-misc/lxqt-connman-applet-0_p20150712/work/lxqt-connman-applet-0_p20150712_build/gentoo_toolchain.cmake  /var/tmp/portage/net-misc/lxqt-connman-applet-0_p20150712/work/lxqt-connman-applet-0_p20150712
Not searching for unused variables given on the command line.
loading initial cache file /var/tmp/portage/net-misc/lxqt-connman-applet-0_p20150712/work/lxqt-connman-applet-0_p20150712_build/gentoo_common_config.cmake
-- The C compiler identification is GNU 4.9.3
-- The CXX compiler identification is GNU 4.9.3
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:12 (include):
  include could not find load file:

```
LXQtTranslate
```

INFODBUS_GENERATED: /var/tmp/portage/net-misc/lxqt-connman-applet-0_p20150712/work/lxqt-connman-applet-0_p20150712_build/agentadaptor.cpp;/var/tmp/portage/net-misc/lxqt-connman-applet-0_p20150712/work/lxqt-connman-applet-0_p20150712_build/agentadaptor.h;/var/tmp/portage/net-misc/lxqt-connman-applet-0_p20150712/work/lxqt-connman-applet-0_p20150712_build/agentadaptor.moc;/var/tmp/portage/net-misc/lxqt-connman-applet-0_p20150712/work/lxqt-connman-applet-0_p20150712_build/net.connman.Manager.cpp;/var/tmp/portage/net-misc/lxqt-connman-applet-0_p20150712/work/lxqt-connman-applet-0_p20150712_build/net.connman.Manager.h;/var/tmp/portage/net-misc/lxqt-connman-applet-0_p20150712/work/lxqt-connman-applet-0_p20150712_build/net.connman.Manager.moc;/var/tmp/portage/net-misc/lxqt-connman-applet-0_p20150712/work/lxqt-connman-applet-0_p20150712_build/net.connman.Service.cpp;/var/tmp/portage/net-misc/lxqt-connman-applet-0_p20150712/work/lxqt-connman-applet-0_p20150712_build/net.connman.Service.h;/var/tmp/portage/net-misc/lxqt-connman-applet-0_p20150712/work/lxqt-connman-applet-0_p20150712_build/net.connman.Service.moc;/var/tmp/portage/net-misc/lxqt-connman-applet-0_p20150712/work/lxqt-connman-applet-0_p20150712_build/net.connman.Technology.cpp;/var/tmp/portage/net-misc/lxqt-connman-applet-0_p20150712/work/lxqt-connman-applet-0_p20150712_build/net.connman.Technology.h;/var/tmp/portage/net-misc/lxqt-connman-applet-0_p20150712/work/lxqt-connman-applet-0_p20150712_build/net.connman.Technology.moc
CMake Error at CMakeLists.txt:89 (lxqt_translate_desktop):
  Unknown CMake command "lxqt_translate_desktop".

-- Configuring incomplete, errors occurred!

**Comment by surlykke** [comment]
2015-07-18 15:16 GMT+02:00 benkohler notifications@github.com:

> Hello,
> 
> Since the cmake changes in commit 98827f9
> https://github.com/surlykke/lxqt-connman-applet/commit/98827f9cd4b8c8de1111c843932cf05864312f79,
> I can't build lxqt-connman-applet anymore. I hope this isn't my local issue
> but I don't think it is. I don't know cmake at all but it would appear that
> dropping "include(${LXQT_USE_FILE})" makes it unable to find
> lxqt_translate_desktop.
> 
> Hmm.   That line - 'include(${LXQT_USE_FILE})' - was actually the reason
> for 98827f9. It seems the variable LXQT_USE_FILE is no longer set by
> findPackage(lxqt...) - so the line generates an error ('wrong number of
> arguments for include' or something like that).

Are you building against an older version of lxqt? (With older I mean more
than a couple of weeks :-) )
- Chr.

**Comment by benkohler** [comment]
Aha, I am building against the latest official release liblxqt-0.9.0, sounds like I need to be building against git master.

**Comment by surlykke** [comment]
2015-07-18 17:07 GMT+02:00 benkohler notifications@github.com:

> Aha, I am building against the latest official release liblxqt-0.9.0,
> sounds like I need to be building against git master.
> 
> If that's a problem for you, I suppose commit 00c4cf would work with
> liblxqt-0.9.0.
- Chr.

**Comment by benkohler** [comment]
I'll make it work, thanks for the quick response and sorry for the noise
