### ISSUE TITLE
implement internationalisation / localisation

### ISSUE THREAD

**Issue by pmattern** [lxqt/lxqt-connman-applet#8]
Title says it basically all. It would be very nice if LXQt ConnMan Applet was translatable.
Any chance we can see this?

**Comment by surlykke** [comment]
2015-07-21 17:44 GMT+02:00 Peter Mattern notifications@github.com:

> Title says it basically all. It would be very nice if LXQt ConnMan Applet
> was translatable.
> Any chance we can see this?
> 
> Certainly on the todo list :-). Please educate me: How is this done in
> LXQt? I know the plan was to use Pootle, but is it implemented?

If so, maybe connman-applet should do the same. But, of course, we could
just start with a more manual approach - checking in *ts files.
- Chr.

**Comment by pmattern** [comment]
To my knowledge translations are handled like this:

Pootle isn't ready for production yet so everything takes place on GitHub, manually and without automation, see e. g. https://github.com/lxde/lxqt/issues/693#issuecomment-112001283.
The template (?) TS files providing the necessary strings but no translations yet like https://github.com/lxde/lxqt-panel/blob/master/plugin-mainmenu/translations/mainmenu.ts are created from time to time by the devs, see e. g. https://github.com/lxde/lxqt-panel/commits/master/plugin-mainmenu/translations/mainmenu.ts. Sometimes they are adjusted by translators as part of their usual work as well besides this actually [isn't desired](https://github.com/lxde/liblxqt/pull/46).
To do the actual translations those template TS files are simply copied to their language- and/or country-specific counterparts by the translators who submit their work as PR later on. Sometimes translated TS files get deleted the same way, too, e. g. the infamous country-specific German ones that turned out to be useless. Adjustments of translated TS files to changes in the templates is done the same way as well.
A PR comprising all those steps is e. g. lxde/lxqt-session#31.

**Comment by surlykke** [comment]
2015-07-28 20:14 GMT+02:00 Peter Mattern notifications@github.com:

> To my knowledge translations are handled like this:
> 
> Pootle isn't ready for production yet so everything takes place on GitHub,
> manually and without automation, see e. g.lxde/lxqt#693 (comment)
> https://github.com/lxde/lxqt/issues/693#issuecomment-112001283.
> The template (?) TS files providing the necessary strings but no
> translations yet like
> https://github.com/lxde/lxqt-panel/blob/master/plugin-mainmenu/translations/mainmenu.ts
> are created from time to time by the devs, see e. g.
> https://github.com/lxde/lxqt-panel/commits/master/plugin-mainmenu/translations/mainmenu.ts.
> Sometimes they are adjusted by translators as part of their usual work as
> well besides this actually isn't desired
> https://github.com/lxde/liblxqt/pull/46.
> To do the actual translations those template TS files are simply copied to
> their language- and/or country-specific counterparts by the translators who
> submit their work as PR later on. Sometimes translated TS files get deleted
> the same way, too, e. g. the infamous country-specific German ones that
> turned out to be useless. Adjustments of translated TS files to changes in
> the templates is done the same way as well.
> A PR comprising all those steps is e. g. lxde/lxqt-session#31
> https://github.com/lxde/lxqt-session/pull/31.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/surlykke/lxqt-connman-applet/issues/8#issuecomment-125700792
> .
> 
> Ok - thanks for the explanation. I'll add something like this to
> lxqt-connman-applet soonish.

br. Chr.

**Comment by surlykke** [comment]
commits https://github.com/surlykke/lxqt-connman-applet/commit/c08a570d04f5b262a7f29130c5c46dd9e83ad6a8  https://github.com/surlykke/lxqt-connman-applet/commit/639c00d097635c4db0a57638962281da6f3bf60e https://github.com/surlykke/lxqt-connman-applet/commit/fefd0c9e25a9aa3ac0c56a01ec90c4bfb4e25426 and https://github.com/surlykke/lxqt-connman-applet/commit/36af99f867d90735f2f1b0f19cf3d472d5745c6f should fix this. (Though adding of translatable strings to source code may still be needed).
